# Generated by Django 3.2.7 on 2022-01-10 23:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentUid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this payment')),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('CANCELED', 'CANCELED')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
