# Generated by Django 3.2.7 on 2022-01-10 23:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelUid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this app')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationUid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this app')),
                ('username', models.CharField(max_length=80)),
                ('payment_uid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this payment')),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('CANCELED', 'CANCELED')], max_length=15)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('hotel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.hotel')),
            ],
        ),
    ]
